# Prioritzing Hospital Admission According to Emergency Using Machine Learning

---

Dataset Link: https://www.kaggle.com/datasets/ashishsahani/hospital-admissions-data/data

In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading the dataset
data=pd.read_csv('HDHI Admission data.csv')
data

,SNO,MRD No.,D.O.A,D.O.D,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,month year,DURATION OF STAY,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,1,234735,4/1/2017,4/3/2017,81,M,R,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
1,2,234696,4/1/2017,4/5/2017,65,M,R,E,Apr-17,5,...,0,0,0,0,0,0,0,0,0,0
2,3,234882,4/1/2017,4/3/2017,53,M,U,E,Apr-17,3,...,0,0,0,0,0,0,0,0,0,0
3,4,234635,4/1/2017,4/8/2017,67,F,U,E,Apr-17,8,...,0,0,0,0,0,0,0,0,0,0
4,5,234486,4/1/2017,4/23/2017,60,F,U,E,Apr-17,23,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,15753,699585,31/03/2019,04/04/2019,86,F,U,O,Mar-19,5,...,0,0,0,0,0,0,0,0,0,0
15753,15754,699500,3/31/2019,4/1/2019,50,M,R,E,Mar-19,2,...,0,0,0,0,0,0,0,0,0,0
15754,15755,700415,31/03/2019,09/04/2019,82,M,U,E,Mar-19,10,...,0,0,0,0,0,0,0,0,0,0
15755,15756,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0
15756,15757,699524,31/03/2019,03/04/2019,59,F,U,O,Mar-19,4,...,0,0,0,0,0,0,0,0,0,0

In [3]:
# Getting a list of the columns in the dataset
data.columns

Index(['SNO', 'MRD No.', 'D.O.A', 'D.O.D', 'AGE', 'GENDER', 'RURAL',
       'TYPE OF ADMISSION-EMERGENCY/OPD', 'month year', 'DURATION OF STAY',
       'duration of intensive unit stay', 'OUTCOME', 'SMOKING ', 'ALCOHOL',
       'DM', 'HTN', 'CAD', 'PRIOR CMP', 'CKD', 'HB', 'TLC', 'PLATELETS',
       'GLUCOSE', 'UREA', 'CREATININE', 'BNP', 'RAISED CARDIAC ENZYMES', 'EF',
       'SEVERE ANAEMIA', 'ANAEMIA', 'STABLE ANGINA', 'ACS', 'STEMI',
       'ATYPICAL CHEST PAIN', 'HEART FAILURE', 'HFREF', 'HFNEF', 'VALVULAR',
       'CHB', 'SSS', 'AKI', 'CVA INFRACT', 'CVA BLEED', 'AF', 'VT', 'PSVT',
       'CONGENITAL', 'UTI', 'NEURO CARDIOGENIC SYNCOPE', 'ORTHOSTATIC',
       'INFECTIVE ENDOCARDITIS', 'DVT', 'CARDIOGENIC SHOCK', 'SHOCK',
       'PULMONARY EMBOLISM', 'CHEST INFECTION'],
      dtype='object')

In [4]:
# Dropping the irrelevant columns
data.drop(columns = ['SNO', 'MRD No.', 'D.O.A', 'D.O.D', 'month year'], inplace  = True)
data

,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,DURATION OF STAY,duration of intensive unit stay,OUTCOME,SMOKING,ALCOHOL,DM,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,81,M,R,E,3,2,DISCHARGE,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,65,M,R,E,5,2,DISCHARGE,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,53,M,U,E,3,3,DISCHARGE,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,67,F,U,E,8,6,DISCHARGE,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,60,F,U,E,23,9,DISCHARGE,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,86,F,U,O,5,1,DISCHARGE,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15753,50,M,R,E,2,2,EXPIRY,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15754,82,M,U,E,10,5,DISCHARGE,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15755,59,F,U,O,4,2,DISCHARGE,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15756,59,F,U,O,4,2,DISCHARGE,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Encoding the categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['GENDER'] = le.fit_transform(data['GENDER'])
data['RURAL'] = le.fit_transform(data['RURAL'])
data['TYPE OF ADMISSION-EMERGENCY/OPD'] = le.fit_transform(data['TYPE OF ADMISSION-EMERGENCY/OPD'])
data['OUTCOME'] = le.fit_transform(data['OUTCOME'])
data

,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,DURATION OF STAY,duration of intensive unit stay,OUTCOME,SMOKING,ALCOHOL,DM,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,81,1,0,0,3,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,65,1,0,0,5,2,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,53,1,1,0,3,3,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,67,0,1,0,8,6,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,60,0,1,0,23,9,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,86,0,1,1,5,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15753,50,1,0,0,2,2,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15754,82,1,1,0,10,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15755,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15756,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Checking for null values
data.isnull().sum()

AGE                                   0
GENDER                                0
RURAL                                 0
TYPE OF ADMISSION-EMERGENCY/OPD       0
DURATION OF STAY                      0
duration of intensive unit stay       0
OUTCOME                               0
SMOKING                               0
ALCOHOL                               0
DM                                    0
HTN                                   0
CAD                                   0
PRIOR CMP                             0
CKD                                   0
HB                                  252
TLC                                 286
PLATELETS                           285
GLUCOSE                             863
UREA                                241
CREATININE                          247
BNP                                8441
RAISED CARDIAC ENZYMES                0
EF                                 1505
SEVERE ANAEMIA                        0
ANAEMIA                               0
STABLE ANGINA                         0
ACS                                   0
STEMI                                 0
ATYPICAL CHEST PAIN                   0
HEART FAILURE                         0
HFREF                                 0
HFNEF                                 0
VALVULAR                              0
CHB                                   0
SSS                                   0
AKI                                   0
CVA INFRACT                           0
CVA BLEED                             0
AF                                    0
VT                                    0
PSVT                                  0
CONGENITAL                            0
UTI                                   0
NEURO CARDIOGENIC SYNCOPE             0
ORTHOSTATIC                           0
INFECTIVE ENDOCARDITIS                0
DVT                                   0
CARDIOGENIC SHOCK                     0
SHOCK                                 0
PULMONARY EMBOLISM                    0
CHEST INFECTION                       0
dtype: int64

In [7]:
# Dropping rows with null values
data.dropna(inplace = True)
data

,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,DURATION OF STAY,duration of intensive unit stay,OUTCOME,SMOKING,ALCOHOL,DM,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,81,1,0,0,3,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,60,0,1,0,23,9,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,44,1,1,0,10,8,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,56,0,1,0,6,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,52,1,1,0,15,11,2,0,0,1,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,86,0,1,1,5,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15753,50,1,0,0,2,2,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15754,82,1,1,0,10,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15755,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15756,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Dropping all rows which contain the value 'EMPTY'
data = data[data != 'EMPTY'].dropna()
data

,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,DURATION OF STAY,duration of intensive unit stay,OUTCOME,SMOKING,ALCOHOL,DM,...,CONGENITAL,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION
0,81,1,0,0,3,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,60,0,1,0,23,9,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,44,1,1,0,10,8,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,56,0,1,0,6,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,52,1,1,0,15,11,2,0,0,1,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,86,0,1,1,5,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15753,50,1,0,0,2,2,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15754,82,1,1,0,10,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15755,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15756,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Getting info about the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5897 entries, 0 to 15756
Data columns (total 51 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   AGE                              5897 non-null   int64
 1   GENDER                           5897 non-null   int64
 2   RURAL                            5897 non-null   int64
 3   TYPE OF ADMISSION-EMERGENCY/OPD  5897 non-null   int64
 4   DURATION OF STAY                 5897 non-null   int64
 5   duration of intensive unit stay  5897 non-null   int64
 6   OUTCOME                          5897 non-null   int64
 7   SMOKING                          5897 non-null   int64
 8   ALCOHOL                          5897 non-null   int64
 9   DM                               5897 non-null   int64
 10  HTN                              5897 non-null   int64
 11  CAD                              5897 non-null   int64
 12  PRIOR CMP                        5897 non-null   int64
 13  CKD                              5897 non-null   int64
 14  HB                               5897 non-null   object
 15  TLC                              5897 non-null   object
 16  PLATELETS                        5897 non-null   object
 17  GLUCOSE                          5897 non-null   object
 18  UREA                             5897 non-null   object
 19  CREATININE                       5897 non-null   object
 20  BNP                              5897 non-null   object
 21  RAISED CARDIAC ENZYMES           5897 non-null   int64
 22  EF                               5897 non-null   object
 23  SEVERE ANAEMIA                   5897 non-null   int64
 24  ANAEMIA                          5897 non-null   int64
 25  STABLE ANGINA                    5897 non-null   int64
 26  ACS                              5897 non-null   int64
 27  STEMI                            5897 non-null   int64
 28  ATYPICAL CHEST PAIN              5897 non-null   int64
 29  HEART FAILURE                    5897 non-null   int64
 30  HFREF                            5897 non-null   int64
 31  HFNEF                            5897 non-null   int64
 32  VALVULAR                         5897 non-null   int64
 33  CHB                              5897 non-null   int64
 34  SSS                              5897 non-null   int64
 35  AKI                              5897 non-null   int64
 36  CVA INFRACT                      5897 non-null   int64
 37  CVA BLEED                        5897 non-null   int64
 38  AF                               5897 non-null   int64
 39  VT                               5897 non-null   int64
 40  PSVT                             5897 non-null   int64
 41  CONGENITAL                       5897 non-null   int64
 42  UTI                              5897 non-null   int64
 43  NEURO CARDIOGENIC SYNCOPE        5897 non-null   int64
 44  ORTHOSTATIC                      5897 non-null   int64
 45  INFECTIVE ENDOCARDITIS           5897 non-null   int64
 46  DVT                              5897 non-null   int64
 47  CARDIOGENIC SHOCK                5897 non-null   int64
 48  SHOCK                            5897 non-null   int64
 49  PULMONARY EMBOLISM               5897 non-null   int64
 50  CHEST INFECTION                  5897 non-null   object
dtypes: int64(42), object(9)
memory usage: 2.3+ MB

In [10]:
# Converting all columns to numeric
data = data.apply(pd.to_numeric, errors='coerce')

In [11]:
# Defining approximate thresholds for numerical parameters
lower_hb_threshold, upper_hb_threshold = 12, 17.5
lower_leukocytes_threshold, upper_leukocytes_threshold = 4000, 11000
lower_platelets_threshold, upper_platelets_threshold = 150000, 450000
upper_glucose_threshold = 240
upper_urea_threshold = 20
lower_creatinine_threshold, upper_creatinine_threshold = 0.6, 1.3
upper_bnp_threshold = 100
lower_ef_threshold, upper_ef_threshold = 50, 70

In [12]:
# Defining a function to determine priority based on conditions
def classify_priority(row):
    # Low priority for outpatient admissions
    if row['TYPE OF ADMISSION-EMERGENCY/OPD'] == 1:
        return 'Low'
    # High priority for emergency patients with specific critical conditions
    elif row['TYPE OF ADMISSION-EMERGENCY/OPD'] == 0 and (
        row['CAD'] == 1 or
        row['PRIOR CMP'] == 1 or
        row['CKD'] == 1 or
        row['RAISED CARDIAC ENZYMES'] == 1 or
        row['SEVERE ANAEMIA'] == 1 or
        row['STABLE ANGINA'] == 1 or
        row['ACS'] == 1 or
        row['STEMI'] == 1 or
        row['HEART FAILURE'] == 1 or
        row['HFREF'] == 1 or
        row['HFNEF'] == 1 or
        row['VALVULAR'] == 1 or
        row['CHB'] == 1 or
        row['SSS'] == 1 or
        row['AKI'] == 1 or
        row['CVA INFRACT'] == 1 or
        row['CVA BLEED'] == 1 or
        row['AF'] == 1 or
        row['VT'] == 1 or
        row['CONGENITAL'] == 1 or
        row['INFECTIVE ENDOCARDITIS'] == 1 or
        row['DVT'] == 1 or
        row['CARDIOGENIC SHOCK'] == 1 or
        row['SHOCK'] == 1 or
        row['PULMONARY EMBOLISM'] == 1 or
        row['CHEST INFECTION'] == 1
    ) and (
        row['HB'] < lower_hb_threshold or
        row['HB'] > upper_hb_threshold or
        row['TLC'] < lower_leukocytes_threshold or
        row['TLC'] > upper_leukocytes_threshold or
        row['PLATELETS'] < lower_platelets_threshold or
        row['PLATELETS'] > upper_platelets_threshold or
        row['GLUCOSE'] > upper_glucose_threshold or
        row['UREA'] > upper_urea_threshold or
        row['CREATININE'] > upper_creatinine_threshold or
        row['CREATININE'] < lower_creatinine_threshold or
        row['BNP'] > upper_bnp_threshold or
        row['EF'] < lower_ef_threshold or
        row['EF'] > upper_ef_threshold
    ):
        return 'High'
    # Medium priority for other emergency patients
    else:
        return 'Medium'

In [13]:
# Creating the priority column using the above function
data['Priority'] = data.apply(classify_priority, axis=1)
data

,AGE,GENDER,RURAL,TYPE OF ADMISSION-EMERGENCY/OPD,DURATION OF STAY,duration of intensive unit stay,OUTCOME,SMOKING,ALCOHOL,DM,...,UTI,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,INFECTIVE ENDOCARDITIS,DVT,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION,Priority
0,81,1,0,0,3,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,High
4,60,0,1,0,23,9,1,0,0,0,...,0,0,0,0,0,0,0,0,0,High
5,44,1,1,0,10,8,1,0,0,1,...,0,0,0,0,0,0,0,0,0,High
6,56,0,1,0,6,2,1,0,0,1,...,0,0,0,0,0,0,0,0,0,High
10,52,1,1,0,15,11,2,0,0,1,...,0,0,0,0,0,1,1,0,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,86,0,1,1,5,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,Low
15753,50,1,0,0,2,2,2,0,0,1,...,0,0,0,0,0,0,0,0,0,High
15754,82,1,1,0,10,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,High
15755,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Low
15756,59,0,1,1,4,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Low

In [15]:
# Check the count of each priority level
priority_counts = data['Priority'].value_counts()

# Display the count of each priority level
print(priority_counts)

High      4586
Low       1151
Medium     160
Name: Priority, dtype: int64